### ISSUE TITLE
Avalon Streaming bits per symbol mismatch

### ISSUE THREAD

**Issue by tvannoy** [fpga-open-speech-tools/simulink_codegen#13]
The autogenerated Platform Designer components use 8 bits per symbol, but the codec and headphone amplifier use 32 bits per symbol. This mismatch causes an error in Platform Designer. 

Either option is totally fine; we just need to be consistent. 

This change needs to happen in the tcl script autogen files.

**Comment by audiologic-vannoy** [comment]
8 data bits per symbol was simply hard coded into the python files. Closed by dc1a83b9ec5c4429c66a6175efb53d8048b53b97
