### ISSUE TITLE
Remove fixed_num struct from driver code

### ISSUE THREAD

**Issue by tvannoy** [fpga-open-speech-tools/simulink_codegen#19]
The fixed_num struct
```c
struct fixed_num {
  int integer;
  int fraction;
  int fraction_len;
};
```
does not appear to be used anywhere, so there's no need for it to be in the device driver c files. 

According to the autogenerated comments, the struct is created in the `CreateMiscTopOfFile` method

**Comment by fe-wickham** [comment]
Looks like the fixed_num struct was used by an implementation of set_fixed_num function, however, we are using the function defined in custom_functions.h, not the one in the device_drivers folder. I will look at removing the SetFixedNum file as well

**Comment by tvannoy** [comment]
Sounds good. I don't know if I'm a fan of having the functions in custom_functions.h inlined into the kernel modules, but I guess it's just a matter of style probably.
