### ISSUE TITLE
Reduce system clock rate to make timing closure easier

### ISSUE THREAD

**Issue by tvannoy** [fpga-open-speech-tools/simulink_codegen#24]
As we currently implement them, the Simulink models only do computation for one system clock cycle (98.304 MHz) every 96 kHz. Students have been having problems meeting timing closure with some of the more complicated Simulink models. 

Since the Audio Mini isn't intended for super high-performance designs, we probably can get away with a much slower system clock than 98.304 MHz. Using a slower clock should make meeting timing closure somewhat easier.

**Comment by rksnider** [comment]
Agreed.  Maybe set it to the mclock rate (12.288 MHz) as a default setting.
