### ISSUE TITLE
Refactor Avalon wrapper codegen

### ISSUE THREAD

**Issue by audiologic-vannoy** [fpga-open-speech-tools/simulink_codegen#3]
There's a lot of duplication and unused code. The architecture is starting to get messy

## notable problems
- registers are passed in as "registers" and "mm_signal"
  - both are used in separate places
- multiple data type conversion functions are defined, but only one is used

## improvement ideas
- put the data width and fractional width in the json file, rather than parsing with python
  - this would require parsing the string in matlab instead

**Comment by tvannoy** [comment]
@fe-wickham is rewriting this to be object oriented
